AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: "app.lambda_handler"
    Runtime: "python3.8"

Resources:
  EdgeLambdaMyBasicRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EdgeLambdaMyBasicRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/service-role/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

  ViewerRequest:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "ImgResizerViewerRequest"
      Description: "covert querystring to path"
      CodeUri: "ViewerRequest/"
      AutoPublishAlias: "prod"
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt EdgeLambdaMyBasicRole.Arn

  OriginResponse:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "ImgResizerOriginResponse"
      # sharpライブラリに依存するためNodeJSのラインタイムを使います
      Runtime: "nodejs12.x"
      Handler: "index.handler"      
      Description: "create resized image if not exists"
      CodeUri: "OriginResponse/"
      AutoPublishAlias: "prod"
      MemorySize: 512
      Timeout: 10
      Role: !GetAtt EdgeLambdaMyBasicRole.Arn
